version: '3'
services:
  jenkins-master:
    image: 'jenkins/jenkins:latest'
    user: root
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'jenkins-data:/var/jenkins_home'
    ports:
      - "8081:8080"
    volumes_from:
      - jenkins-data
  
  jenkins-data:
    image: 'debian:jessie'
    volumes:
      - 'jenkins-data:/var/jenkins_home'

  app:
    image: 'dotnet7'
    ports:
      - "8082:80"

  cypress:
    image: 'cypress'
    depends_on:
      - app
    volumes:
      - ./tan/Cypress:/e2e/cypress
    command: ["sleep", "infinity"]

volumes:
  jenkins-data:
